### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by neeraj-2** [publiclab/lego-spectrometer#1]
**Actual Behaviour:**

Right Now ,the front-end part of site looks pretty good ,but mobile view does not seem perfect.

**Expected Behavior:**

It should work well on mobile screens too
![desktop_view](https://user-images.githubusercontent.com/56186425/91656230-c4909f00-ead4-11ea-8b6f-f4dc93e1c718.PNG)
![mobile_view](https://user-images.githubusercontent.com/56186425/91656232-ca868000-ead4-11ea-926e-8eb4f09eec15.PNG)

**Would u like to work on this issue?**
open for all!

**Comment by jywarren** [comment]
Hi, is this on PublicLab.org? Perhaps you could open this on https://github.com/publiclab/plots2/? Thank you!!
